### ISSUE TITLE
crashing in heat

### ISSUE THREAD

**Issue by markoman15** [KSP-RO/SovietRockets#10]
I have been said to in tlyerraiz stream that sent rocket should be in space. I have no been able to do that. I have sent rocket up and down in explosive casket it has gone and my kerbal is now dead. The building is flames and I can't send more. When I go up it comes down since using mod q12 menu when engines don't start. Gravity well is not enough so changes made and now it stuck in upper position of shoe. I am sending message to market commerce in steam for refund to report you for fraud.

**Comment by Bornholio** [comment]
You may need to solve the engine start you posted on in #9 first.  Buildings can be repaired by right clicking on the structure in space center and selecting the repair building button.  Feel free to report to any agencies you would like about subsequent fraud investigations.

**Comment by markoman15** [comment]
I have man mailed repair to fix building but issues remain. I send them again and line not respond to code. Building remained in pieces of many. I am needed much of monetize to send for repair please send money.

**Comment by Bornholio** [comment]
Funds in game if you need. Pressing Mod-F12 and button to add funds to total +1000 or +100000
Or monetize using mission control new contract!
