### ISSUE TITLE
configuration of  missile blankets

### ISSUE THREAD

**Issue by markoman15** [KSP-RO/SovietRockets#11]
I have add more chip to keyboard and now the mod cause my game to load. With load I have been see that beyond cartridge pack the computer have evolution of access in the zone of violators for the linked librarians. I now cannot see past the town and my screen says loading has been extinguished. I have put for refund and await the transfer for funding. Please respond.

**Comment by Bornholio** [comment]
If you are having loading problems and game errors please post your output_log.txt using an online service or prefereably use the instructions found at https://forum.kerbalspaceprogram.com/index.php?/forum/70-technical-support-pc-modded-installs/

**Comment by Starwaster** [comment]
Operator, I need an exit.

**Comment by Bornholio** [comment]
Exit left at station 4!  take the red pill.

**Comment by markoman15** [comment]
For pills of suppository I have no to have taken. I believe that between 6 years and beyond the wall there are times when those who see are not. Please help as my imagery has stopped and now only black remains.

**Comment by Bornholio** [comment]
I would suggest delete mod and use installer to check files or reinstall.
