### ISSUE TITLE
broken space tube

### ISSUE THREAD

**Issue by markoman15** [KSP-RO/SovietRockets#12]
With no help I have not fixed to work of my computer. Asking has not been received in ways understood by concentrated humans. Tylerraiz has said that beyond ways of dogma telegraph that I have seen the stars but only the ground visible. From facing up the down is only not seen. I have assembled new craft but jiggle tubes have caused explosive kidney failure. Please send help or refund.

**Comment by Bornholio** [comment]
You may need to seek medical attention for any damage to your body.  Please contact your local emergency services if you are in need.

**Comment by Bornholio** [comment]
If you need more detailed support https://forum.kerbalspaceprogram.com/index.php?/topic/163863-how-to-get-support/ is advisable to read. if you need help in a language other than english. Feel free to ask in that language as we have people in the community that speak other languages.
