### ISSUE TITLE
Luna 1/2 Mission in KSP RO failing to reach the Moon

### ISSUE THREAD

**Issue by astro-stan** [KSP-RO/SovietRockets#17]
Hello,

I am playing KSP 1.6.1 with RO, RP-1, and a bunch of other mods, however I am struggling to replicate the Luna missions. I am using the pre-made "RN Stock Luna 2", but I am still unable to reach/impact the moon.

Correct me if I am wrong, but here is my understanding of how the real mission went:
1. Launched from Baikonur
2. Reached an altitude of about 200-300km (could not find an accurate number), before the main engine of the second stage ran out of fuel
3. Removed the fairing
4. Decoupled the upper stage, and lit it's vernier engines
5. At the right time it lit the upper stage's main engine as well (the RD-0105)
6. When the impact orbit was reached (or in the case of Luna 1, slightly after) the engines shut down.
7. Decoupled the probe
8. Impacted/flew close by the Moon

Here is what I am doing in KSP RO using the RN Stock Luna 2 craft:

1. Set the Moon as target
2. Wait until the inclination of the orbit is as close as possible to the one of the Moon (around 17.5 degrees, according to Mechjeb's Rendezvous Planner) and the moon is in a proper position (not too far behind or in front of what would become my transfer orbit trajectory)
3. Launch (from Baikonur)
4. Reach about 200-300 km, decouple, light verniers, etc.
5. Use Mechjeb's Maneuver Planner to create a node automatically
   5.1. Select "bi-impulsive (Hohmann) transfer to target"
   5.2. Select "intercept only, no capture burn (impact/flyby)"
   5.3. Select "create node at next apoapsis", because otherwise it creates a node after one orbit has passed, and the craft is not in orbit
   5.4. Click "create node"
6. Align the upper stage with the node, wait untill the required burn time is split 50/50 before and after the node.
7. light the main engine, burn until fuel runs out.

The craft itself (according to Mechjeb's Dv stats has 13176 m/s of Dv. However no matter what I do I still fall short by at least 1000 m/s of Dv on the upper stage.

I tried warping back and forward before launching to change the position of the Moon in it's orbit, tried playing with the inclination and initial altitude, but no luck.

Am I doing someting wrong, or could this be a configuration issue?

**Comment by Gordon-Dry** [comment]
It got "stock" in the name.

Try "RO RN Luna 2.craft" shipped with RO.

**Comment by raidernick** [comment]
I'm not helping you fly the mission. You are using the stock craft file most likely, and even if you were using the RO one I know for a fact it works. I've done the mission myself several times and had others test it, including some twitch streamers. It's also been used in youtube videos based on the mission and it worked fine there also. It's not a config issue but user error, and as I said I don't provide support for HOW to fly the missions, only that the parts work as intended which they do.

**Comment by astro-stan** [comment]
Yes, I'm sorry for the confusion, 
I did not even realize there were two crafts (which should have been obvious because of the name).
With the proper craft and some more practice I managed to impact the moon.

Thank you for your time.
