### ISSUE TITLE
MIRV Update

### ISSUE THREAD

**Issue by victor-lopez17** [KSP-RO/SovietRockets#19]
I believe this is not likely to happen but best to try. I’ve been trying to get the MIRV nuclear warheads to work with both the old and the new North Kerbin Dynamic plugins but I didn’t get it. Maybe I did something wrong or maybe it needs an update. If the latter is the case, I’d be grateful if it happened.

**Comment by raidernick** [comment]
They will never be updated. It was just a test thing that I did and it never worked properly so I gave up on it.
