### ISSUE TITLE
Remove weird parts

### ISSUE THREAD

**Issue by markoman15** [KSP-RO/SovietRockets#7]
I want you to remove the weird parts I see in the pictures on the page. I don't see them in real pictures and in tylerraiz stream earlier he said that the picture I sent was this exact mod but I don't see that picture here, please fix it now.

**Comment by Bornholio** [comment]
You might need to elaborate on what parts you are requesting be removed.  If you want you can manually remove any part from the folders along with its model, texture and normal files to eliminate it from the game.
