### ISSUE TITLE
Memory more

### ISSUE THREAD

**Issue by markoman15** [KSP-RO/SovietRockets#8]
I try to load this but i said to not have enough memory. I was having 2gb of memory and in tylerraiz stream it said that this was not enough. I want you to make this fix to work with 2gb please now.

**Comment by Bornholio** [comment]
Stock KSP will have some success running on that little RAM but if you use any mods you will likely run memory allocations of 4-7GB.  It is unlikely even with heavy optimization to reduce your RAM usage significantly. You may find that you can choose a few individual SovietRockets parts and load only those (.cfg, .mu, .dds and NRM.dds) files needed for them. along with a reduction of uneeded stock parts.
