### ISSUE TITLE
fix my engines

### ISSUE THREAD

**Issue by markoman15** [KSP-RO/SovietRockets#9]
I install this and my engines no work. I have real solar mod and they said tylerraiz stream I need realism mod and with mod my engines are blubber sparks and noise but it not starting. I have the liquid dynamite and propellant oxidation in the nose but they not start when launch. I demand that this me fixed my game broke now, please send refund.

**Comment by Bornholio** [comment]
You will need to install Realism Overhaul along with all dependencies such as Real Fuels, FAR and other associated mods. Feel free to post your Output_log.txt from the KSP_x64_Data folder from your latest attempt to run the game using a acceptable download service such as Dropbox.
